name: CI
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - conda-env: base
            os: ubuntu-latest
            installer-url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            python-version: "3.10"
          - conda-env: base
            os: ubuntu-latest
            installer-url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            python-version: "3.11"
          - conda-env: base
            os: ubuntu-latest
            installer-url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            python-version: "3.12"
          - conda-env: base
            os: ubuntu-latest
            installer-url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            python-version: "3.13"
          - conda-env: base
            os: ubuntu-latest
            installer-url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            python-version: "3.14"
          - conda-env: base
            os: macos-15-intel
            installer-url: https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
            python-version: "3.14"
          - conda-env: base
            os: macos-latest
            installer-url: https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh
            python-version: "3.14"
          - conda-env: base
            os: windows-latest
            installer-url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
            python-version: "3.14"
    env:
      PYVER: ${{ matrix.cfg.python-version }}
      CONDA_ENV: ${{ matrix.cfg.conda-env }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        installer-url: ${{ matrix.cfg.installer-url }}
        activate-environment: test
        environment-file: ${{ matrix.cfg.conda-env }}.yaml
        python-version: ${{ matrix.cfg.python-version }}
        auto-activate-base: false
    - name: Install
      shell: bash -l {0}
      run: | # Install molsym
        conda install -n test pip -y
        python -m pip install . --no-deps
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest --cov="molsym" --color=yes --cov-report=xml test/
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: false
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true
